<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="fr">
<head>
<title>index</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="index" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 18.0.4 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="5" />
<link rel="canonical" href="/index.php" />
<?php if ($_SERVER["PHP_SELF"] == "/index.php") { ?>
<link rel="alternate" hreflang="fr" href="<?php echo $website->virtualhost; ?>/index.php" />
<?php } ?>
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="a59c65eb" async src="/javascript.js.php"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-index">
<!-- Enter here your HTML content. Add a section with an id tag and tag contenteditable="true" if you want to use the inline editor for the content  -->

<?php includeContainer('header'); ?>


<section id="mysection1" contenteditable="true">
        <main>
            <section class="hero">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5 col-12 m-auto">
                            <div class="heroText">
                                <h1 class="text-white mb-lg-5 mb-3">
                                    Délicieuse Pâtisserie
                                </h1>

                                <div class="c-reviews my-3 d-flex flex-wrap align-items-center">
                                    <div
                                        class="d-flex flex-wrap align-items-center">
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-7 col-12">
                            <div
                                id="carouselExampleCaptions"
                                class="carousel carousel-fade hero-carousel slide"
                                data-bs-ride="carousel"
                            >
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <div class="carousel-image-wrap">
                                            <img
                                                src="image/Bpo/slide/jay-wennington-N_Y88TWmGwA-unsplash.jpg"
                                                class="img-fluid carousel-image"
                                                alt=""
                                            />
                                        </div>

                                        <div class="carousel-caption">
                                            <h4 class="hero-text">
                                                Fraîcheur garantie
                                            </h4>
                                        </div>
                                    </div>

                                    <div class="carousel-item">
                                        <div class="carousel-image-wrap">
                                            <img
                                                src="image/Bpo/slide/jason-leung-O67LZfeyYBk-unsplash.jpg"
                                                class="img-fluid carousel-image"
                                                alt=""
                                            />
                                        </div>

                                        <div class="carousel-caption">
                                            <div
                                                class="d-flex align-items-center"
                                            >
                                                <h4 class="hero-text">Steak</h4>

                                                <span class="price-tag ms-4"
                                                    >26.50<small>€</small></span
                                                >
                                            </div>
                                        </div>
                                    </div>

                                    <div class="carousel-item">
                                        <div class="carousel-image-wrap">
                                            <img
                                                src="image/Bpo/slide/ivan-torres-MQUqbmszGGM-unsplash.jpg"
                                                class="img-fluid carousel-image"
                                                alt=""
                                            />
                                        </div>

                                        <div class="carousel-caption">
                                            <div
                                                class="d-flex align-items-center"
                                            >
                                                <h4 class="hero-text">
                                                    Sausage Pasta
                                                </h4>

                                                <span class="price-tag ms-4"
                                                    >18.25<small>€</small></span
                                                >
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <button
                                    class="carousel-control-prev"
                                    type="button"
                                    data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide="prev"
                                >
                                    <span
                                        class="carousel-control-prev-icon"
                                        aria-hidden="true"
                                    ></span>
                                    <span class="visually-hidden"
                                        >Previous</span
                                    >
                                </button>

                                <button
                                    class="carousel-control-next"
                                    type="button"
                                    data-bs-target="#carouselExampleCaptions"
                                    data-bs-slide="next"
                                >
                                    <span
                                        class="carousel-control-next-icon"
                                        aria-hidden="true"
                                    ></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="overlay"></div>
            </section>

            <section class="menu section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="text-center mb-lg-5 mb-4">
                                Nos produits
                            </h2>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/breakfast/brett-jordan-8xt8-HIFqc8-unsplash.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Vinnoiserie</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Matinale</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >2.5<small>DH</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/lunch/Le Bon Pain.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Boulangerie</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Le Bon Pain</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >2.5<small>DH</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/dinner/keriliwi-c3mFafsFz2w-unsplash.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Petits Fours</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Marocaine</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >45<small>DH</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/dinner/farhad-ibrahimzade-ZipYER3NLhY-unsplash.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Pâtisserie</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Délices</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >86<small>dh</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/breakfast/louis-hansel-dphM2U1xq0U-unsplash.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Breakfast</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Burger Set</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >20.50<small>€</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 col-12">
                            <div class="menu-thumb">
                                <div class="menu-image-wrap">
                                    <img
                                        src="image/Bpo/lunch/farhad-ibrahimzade-D5c9ZciQy_I-unsplash.jpg"
                                        class="img-fluid menu-image"
                                        alt=""
                                    />

                                    <span class="menu-tag bg-warning"
                                        >Lunch</span
                                    >
                                </div>

                                <div
                                    class="menu-info d-flex flex-wrap align-items-center"
                                >
                                    <h4 class="mb-0">Healthy Soup</h4>

                                    <span
                                        class="price-tag bg-white shadow-lg ms-4"
                                        >34.20<small>€</small></span
                                    >

                                    <div
                                        class="d-flex flex-wrap align-items-center w-100 mt-2"
                                    >
                                        <div class="reviews-stars">
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i
                                                class="bi-star-fill reviews-icon"
                                            ></i>
                                            <i class="bi-star reviews-icon"></i>
                                            <i class="bi-star reviews-icon"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>

</section>


<?php includeContainer('footer'); ?>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 5); dolWebsiteIncrementCounter(3, "page", 5);
// END PHP ?>
